version: '2'
services:
  zookeeper:
    container_name: er-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: er-kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICs: "ErJuer:1:1"  # Topic명:Partition개수:Replica개수 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
